### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/smtp#26] opened 2023-11-17 23:30 UTC
When trying to uninstall I get:  Call to a member function get() on null 

Website can't seem to authenticate to Office365, so I am trying to uninstall and reinstall clean.  This was an upgrade from Drupal 7.

SMTP Version 1.x-1.7.1

**Comment by indigoxela** [comment] 2024-02-23 11:45
Confirmed, the problem is a non-existent config variable here:
https://github.com/backdrop-contrib/smtp/blob/1.x-1.x/smtp.install#L47

```
$config = config('smtp.settings');
```

**Comment by bugfolder** [comment] 2024-02-23 12:28
PR submitted that fixes it.

**Comment by indigoxela** [comment] 2024-02-23 12:32
@bugfolder wow, that was fast!

I can confirm, that the patch fixes the problem. :+1:

**Comment by yorkshire-pudding** [comment] 2024-08-10 23:26
I can also confirm that this fixes the issue. @jenlampton please can you merge and release?

**Comment by herbdool** [comment] 2024-11-01 23:38
Merged on behalf of the @backdrop-contrib/bug-squad

**Closed as completed** 2024-11-01 23:38 UTC
