### ISSUE TITLE
Undefined variable $config dans smtp_uninstall()

### ISSUE THREAD

**Issue by drupix** [backdrop-contrib/smtp#37] opened 2024-05-21 14:27 UTC
There is a small bug in hook_uninstall() of the mudule:

`$mail_system = $config->get('smtp_previous_mail_system');`

should be changed with:

`$mail_system = config_get('smtp_previous_mail_system');`

**Comment by yorkshire-pudding** [comment] 2024-08-10 23:24
This issue is a duplicate of #26 which has a Pull Request at #30

**Closed as not planned by yorkshire-pudding** 2024-08-10 23:24 UTC
Labels: duplicate
